flowchart TD
    classDef ltrGraph fill:#797;
    classDef rtlGraph fill:#779,stroke-width:4px;
    classDef noneGraph fill:#977,stroke-width:4px,stroke-dasharray: 5 5;
    subgraph legend["Legend"]
    legend0["Left-to-right"]:::ltrGraph
    legend1("Right-to-left"):::rtlGraph
    legend2["Requires parentheses"]:::noneGraph
    end
    A["(...)"]
    subgraph primary[" "]
    primary0["a()"]
    primary1["a[]"]
    primary2["a.b"]
    end
    subgraph unary[" "]
    unary0("-a")
    unary1("!a")
    unary2("~a")
    unary3("*a")
    unary4("&a")
    end
    subgraph multiplicative[" "]
    multiplicative0["a*b"]
    multiplicative1["a/b"]
    multiplicative2["a%b"]
    end
    subgraph additive[" "]
    additive0["a+b"]
    additive1["a-b"]
    end
    subgraph shift[" "]
    shift0["a<<b"]
    shift1["a>>b"]
    end
    subgraph relational[" "]
    relational0["a<b"]
    relational1["a>b"]
    relational2["a<=b"]
    relational3["a>=b"]
    relational4["a==b"]
    relational5["a!=b"]
    end
    class primary ltrGraph;
    class unary rtlGraph;
    class multiplicative ltrGraph;
    class additive ltrGraph;
    class shift noneGraph;
    class relational noneGraph;
    A-->primary
    primary-->unary
    unary-->multiplicative
    unary-->shift
    unary-->binary0["a&b"]:::ltrGraph;
    unary-->binary1["a|b"]:::ltrGraph;
    unary-->binary2["a^b"]:::ltrGraph;
    multiplicative-->additive
    additive-->relational
    shift-->relational
    relational-->shortcircuit0["a&&b"]:::ltrGraph;
    relational-->shortcircuit1["a||b"]:::ltrGraph;
