name: 'gpuweb-custom-action'
description: 'This action runs a container with all necessary tools to validate source'
inputs:
  check-repo-clean:
    description: 'Check if repo is clean after build'
    required: false
    default: 'ON'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mehmetoguzderin/gpuweb:main'
  args:
    - ${{ inputs.check-repo-clean }}
