sequenceDiagram
    Note over Content timeline: mapState: "unmapped"
    Note over Device timeline: [[state]]: "unmapped"
    Content timeline ->> Device timeline: mapAsync()
    Note over Content timeline: mapState: "pending"
    Note over Device timeline: (failure, state unchanged)
    Device timeline ->> Content timeline: mapAsync() response
    Note over Content timeline: mapState: "unmapped"
