sequenceDiagram
    Note over Content timeline: [[mapping]] is null<br>[[pending_map]] is null
    Note over Device timeline: [[internal state]] is "available"
    Content timeline ->> Device timeline: mapAsync()
    Note over Content timeline: [[mapping]] is null<br>[[pending_map]] is non-null
    Note over Device timeline: (failure, state unchanged)
    Device timeline ->> Content timeline: mapAsync() response
    Note over Content timeline: [[mapping]] is null<br>[[pending_map]] is null
