sequenceDiagram
    Note over Content timeline: [[mapState]]: "unmapped"
    Note over Device timeline: [[deviceTimelineState]]: "available"
    Content timeline ->> Device timeline: mapAsync()
    Note over Content timeline: [[mapState]]: "pending"
    Note over Device timeline: [[deviceTimelineState]]: "unavailable"
    Device timeline ->> Content timeline: mapAsync() response
    Note over Device timeline: [[deviceTimelineState]]: "unavailable"
    Note over Content timeline: [[mapState]]: "mapped"
    Content timeline ->> Device timeline: unmap()
    Note over Content timeline: [[mapState]]: "unmapped"
    Note over Device timeline: [[deviceTimelineState]]: "available"
