sequenceDiagram
    Note over Content timeline: [[mapping]] is null<br>[[map_requests]] is empty
    Note over Device timeline: [[deviceTimelineState]] is "available"
    Content timeline ->> Device timeline: mapAsync()
    Note over Content timeline: [[mapping]] is null<br>[[map_requests]] has 1 element
    Note over Device timeline: [[deviceTimelineState]] is "unavailable"
    Device timeline ->> Content timeline: mapAsync() response
    Note over Device timeline: [[deviceTimelineState]] is "unavailable"
    Note over Content timeline: [[mapping]] is non-null<br>[[map_requests]] is empty
    Content timeline ->> Device timeline: unmap()
    Note over Content timeline: [[mapping]] is null<br>[[map_requests]] is empty
    Note over Device timeline: [[deviceTimelineState]] is "available"
