name: Build and publish to GitHub Pages

# Workflow runs on pushes to the main branch. It builds all Bikeshed documents
# (specs and explainers/references) and some supplemental materials (IDL and
# grammar) and pushes them to GitHub Pages.
#
# The "workflow_dispatch" hook allows admins to trigger the workflow manually
# from GitHub's UI.

on:
  push:
    branches: [main]
    paths:
      - '.github/**'
      - 'tools/**'
      - 'spec/**'
      - 'wgsl/**'
      - 'explainer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Populate out/
        run: |
          export PATH="$(python3 -m site --user-base)/bin:${PATH}"
          pip3 install bikeshed==3.7.0
          mkdir ./out
          ./compile.sh

      - name: Deploy to GitHub Pages
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: out
