name: publish-TR-webgpu

# On pull requests, verify the WebGPU spec builds using spec-prod.
# On pushes to the main branch, build and publish to /TR:
# https://www.w3.org/TR/webgpu/
#
# Note: spec-prod uses the latest bikeshed instead of a pinned version

on:
  pull_request:
    # Runs on all paths because otherwise we'd need a stub to be able to make
    # the check required. See:
    # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'spec/**'
  workflow_dispatch:

jobs:
  publish-TR-webgpu:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: spec/index.bs
          BUILD_FAIL_ON: warning
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN_WEBGPU }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-gpu/2021Apr/0004.html
          W3C_BUILD_OVERRIDE: |
            status: WD
