name: Build, validate and publish spec to GitHub Pages and /TR

# Workflow runs once per spec (WebGPU, WGSL and explainer) on pull requests and
# on pushes to the main branch that touch the spec. For pull requests, it makes
# sure that the spec can be generated and that markup is valid. For pushes, it
# also deploys the generate spec to GitHub Pages and to /TR for WebGPU and WGSL.
# The "workflow_dispatch" hook allows admins to trigger the workflow manually
# from GitHub's UI.
#
# Workflow uses the w3c/spec-prod action, see base multi-spec repo example at:
# https://github.com/w3c/spec-prod/blob/main/docs/examples.md#multiple-specs-in-same-repository

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - '.github/**'
      - 'spec/**'
      - 'wgsl/**'
      - 'explainer/**'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - source: spec/index.bs
            destination: index.html
            echidna_token: ECHIDNA_TOKEN_WEBGPU
            w3c_build_override_status: WD
          - source: wgsl/index.bs
            destination: wgsl/index.html
            echidna_token: ECHIDNA_TOKEN_WGSL
            w3c_build_override_status: WD
          - source: explainer/index.bs
            destination: explainer/index.html
            # Explainer is not published to /TR, no echidna_token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and validate spec, publish to GitHub Pages and /TR
        uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
          BUILD_FAIL_ON: warning
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets[matrix.echidna_token] }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-gpu/2021Apr/0004.html
          W3C_BUILD_OVERRIDE: |
            group: gpuwg
            status: ${{ matrix.w3c_build_override_status }}
