name: Build, validate and publish specs to /TR

# Workflow runs once per published spec (WebGPU, WGSL) on pull requests and
# on pushes to the main branch that touch the spec. For pull requests, it makes
# sure that the spec can be generated and that markup is valid. For pushes, it
# also deploys the generated spec to /TR for WebGPU and WGSL.
#
# The "workflow_dispatch" hook allows admins to trigger the workflow manually
# from GitHub's UI.
#
# Workflow uses the w3c/spec-prod action, see base multi-spec repo example at:
# https://github.com/w3c/spec-prod/blob/main/docs/examples.md#multiple-specs-in-same-repository
# Note, spec-prod can publish to gh-pages as well, but we need a custom publish
# step to publish additional files as well, so we use that instead of making
# many separate gh-pages commits (one per bikeshed file + one for extra files).

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - '.github/**'
      - 'tools/**'
      - 'spec/**'
      - 'wgsl/**'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - source: spec/index.bs
            echidna_token: ECHIDNA_TOKEN_WEBGPU
            w3c_build_override_status: WD
          - source: wgsl/index.bs
            echidna_token: ECHIDNA_TOKEN_WGSL
            w3c_build_override_status: WD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # TODO: spec-prod seems to use the latest bikeshed instead of our pinned version
      - name: Build and validate spec, publish to /TR
        uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: ${{ matrix.source }}
          BUILD_FAIL_ON: warning
          W3C_ECHIDNA_TOKEN: ${{ secrets[matrix.echidna_token] }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-gpu/2021Apr/0004.html
          W3C_BUILD_OVERRIDE: |
            group: gpuwg
            status: ${{ matrix.w3c_build_override_status }}

  wgsl-grammar:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate WGSL grammar
        run: |
          pip3 install tree_sitter==0.19.0
          make -C wgsl validate
