# Refresh the docker image that builds specs.  For example, pull in fresh Bikeshed data files.
name: refresh-custom-action-image

on:
  schedule:
    - cron: '0 0 * * 5'

  push:
    branches: [ "main" ]
    paths:
      - "tools/custom-action/Dockerfile"
      - "tools/custom-action/entrypoint.sh"
  # Allows admins to trigger the workflow manually from GitHub UI or CLI, anytime.
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: tools/custom-action
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
